### ISSUE TITLE
No GNSS device detected on Qwiic bus - when using a mux (multiplexer)

### ISSUE THREAD

**Issue by amaanq** [sparkfun/OpenLog_Artemis_GNSS_Logger#27]
### Subject of the issue
OpenLog Artemis GNSS Logger can't detect or log from ublox F9P GNSS receiver despite being plugged in with the qwiic mux breakout

### Your workbench
* Are you using a microSD card? If so, what size? How is it formatted (FAT, FAT32, or exFat)? FAT32 32gb
* At what frequency are you logging? For example, 10Hz, 1Hz, once every 5 seconds, etc. 1Hz (Every second)
* What version of firmware are you using? This is shown at boot, for example: "Artemis OpenLog GNSS v1.0" Artemis OpenLog GNSS v2.2
* How is OpenLog Artemis wired to your GNSS? qwiic mux breakout
* Which GNSS module are you using? ublox F9P
* How is everything being powered? laptop usb port
* Are there any additional details that may help us help you? I'm on linux, I reset the device already, and the problem did occur after I flashed new firmware though, so I might try downgrading.

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.
No idea to be honest
### Expected behavior
Tell us what should happen
Should be able to edit GNSS settings in a serial terminal or at the very least not have it say `Menu: Configure uBlox GNSS Receiver 
**No GNSS device detected on Qwiic bus**`
### Actual behavior
Tell us what happens instead
Cannot interact with or log data from the GNSS receiver.

**Comment by PaulZC** [comment]
Hi AQ (@amaanq ),

Apologies. The OpenLog Artemis GNSS Logger firmware is not the same as the full [OpenLog Artemis firmware](https://github.com/sparkfun/OpenLog_Artemis). It can only connect to a single GNSS module, and can not connect to it through a mux. This firmware contains no mux detection or port selection support.

Adding mux support would be a huge change...

So, I am sorry, but you can not use a mux with this firmware. You can if you use the full [OpenLog Artemis firmware](https://github.com/sparkfun/OpenLog_Artemis) - but that limits you to logging Position-Velocity-Time only.

Best wishes,
Paul

**Comment by amaanq** [comment]
Hi Paul, thanks for getting back to me pretty quickly,

I have 2 data loggers, one is to log GNSS data and the other to log data from a sonar sensor and both were ideally going to use the mux to get the data from a ublox F9P receiver, but since that's not possible with this GNSS firmware, I'm a bit lost as to how I'd accomplish that. At the same time, the logger that logs sonar has to get the simpler GPS data such as position and time, and I wanted to compare that data with the GNSS data for my own research later on, please let me know of any alternatives or solutions you can think of for this.

Thanks,
Amaan

*edited for grammar/tense inconsistency
